FROM mcr.microsoft.com/devcontainers/base:ubuntu-22.04

RUN apt-get update && apt-get install -y \
    cmake \
    gcc-arm-none-eabi \
    make \
    gdb-multiarch \
    openocd \
    && apt-get clean
